### ISSUE TITLE
Doubts

### ISSUE THREAD

**Issue by mirraaj** [mlpack/jenkins-conf#13]
https://github.com/mlpack/jenkins-conf/blob/2744fe1a18045faaaed8ecea3442b12c172a0789/runTestBins.sh#L4

Hello @rcurtin, I am trying to understand the error you described in https://github.com/mlpack/mlpack/issues/1741 and focussed to solve this asap. I have encountered a confusion doubt over the ```bin``` folder. It contains executable files to run tests in mlpack if I am correct. Could you please let me know if these executables generated are different for different cases?

Also, let me know that if the jenkins generate only important test cases for each PR depending upon the changes made in specific PR?

@zoq @rcurtin @ShikharJ I am trying to rectify this error asap. Please provide your valuable inputs. Thanks

**Comment by rcurtin** [comment]
Right, the file `mlpack_test` will be created in the `bin/` directory.  I don't know if `runTestBins.sh` is the cleanest script in the world...

A long time ago there used to be separate tests built for each bit of functionality... so there would be, e.g., `knn_test`, `kfn_test`, `det_test`, and so on and so forth... so this is why the script gathers all the programs in the `bin/` directory that have a `_test` at the end of them.  But now, there's only `mlpack_test`, so that's a little bit redundant.

**Comment by mirraaj** [comment]
@rcurtin How about we only test the new test files 1000 times using a python script. I am adding a small snippet. This code gives back the name of test files added to a branch. For comparison, I am using the master branch of mlpack to determine the ```diff``` results. Please let me know if this will work on jenkins server. Please note you may need to install ```gitpython``` to run the python script.

`#!/usr/bin/env python

# Import GitPython to compare results
import git

import os, time

# Link to GitHub Repo
# Use os.join_dir to make it universal
repo_dir = "/home/zoro/gsoc/mlpack"

repo = git.Repo(repo_dir)

# Check that the repository is not bare
assert not repo.bare

#Assume that master branch is passing all the test
parent_branch_commit = repo.branches.master.commit
examine_branch_commit = repo.head.commit

#Get
diff_results = repo.git.diff(parent_branch_commit,\
	examine_branch_commit)

diff_results = diff_results.split('\n')

newtests = []
# Each added line has '+' in the beginning of the line
# Each deleted line has '-' in the beginning of the line
# Check if "BOOST_AUTO_TEST_CASE" is there in line added.
# If new test added, save the name of the test file

for line in diff_results:
	if line[0] == "+":
		if 'BOOST_AUTO_TEST_CASE' in line:
			newtests.append(line[22:-1])

# Run the tests in newtests 1000 times to determine the
# stability of the test files.

# print (newtests)`

[https://drive.google.com/open?id=1PRK7VjJVRvJ_kQeeq4Qo65ruRLGdqkBc](url)

**Comment by mirraaj** [comment]
@rcurtin I might need help to integrate ```BOOST_GLOBAL_FIXTURE``` as you described in step 2 in https://github.com/mlpack/mlpack/issues/1741.

Could you let me know, how can we make global fixture that might be able to introduce ```mlpack::math::RandomSeed(std::time(NULL))``` to test the new tests 1000 times.

**Comment by zoq** [comment]
You could just add the random seed to:

https://github.com/mlpack/mlpack/blob/2c91431f2ae10eee336dfbd944dbbb4ba14cc705/src/mlpack/tests/mlpack_test.cpp#L101-L130

**Comment by zoq** [comment]
I see some issues with the script:
- The diff has to contain ``BOOST_AUTO_TEST_CASE``, so this will not cover if I change something inside a test case; we could do a reverse search until we find ``BOOST_AUTO_TEST_CASE`` to solve that.
- The current idea will not run a test if I change something in the codebase that already has a test, which I think would be nice to have. One idea might be to build some form of dependency graph (``CMAKE_EXPORT_COMPILE_COMMANDS`` could be helpful). And run the corresponding tests.

**Comment by mirraaj** [comment]
@zoq I agree with your comments. I skipped the thought of testing `BOOST_AUTO_TEST_CASE` when I change a specific line/code snippet in the project. 

- That sounds better to me. However, I am not sure as of now how to grab the `BOOST_AUTO_TEST_CASE` names. Let me explore a bit more, before I can comment further on this issue.

- Could you please give me an idea on how to use `CMAKE_EXPORT_COMPILE_COMMANDS`. As per my understanding, the tag will help `cmake` to generate `compile_commands.json` which gives exact compiler calls for all translation units of the project in machine-readable form. One thing we can do is to grab the test file name for a particular codebase and capture all the tests using the file `compile_commands.json`. I am still not sure how we can do this, but I think it is worth giving a try.

**Comment by mirraaj** [comment]
@zoq Do you think adding `mlpack::math::RandomSeed(std::time(NULL))` at https://github.com/mlpack/mlpack/blob/2c91431f2ae10eee336dfbd944dbbb4ba14cc705/src/mlpack/tests/mlpack_test.cpp#L113 will work? Should I go ahead and open a PR to add this?

**Comment by zoq** [comment]
Yeah, this should work, we should add another cmake option that enables the random seed test feature.

**Comment by mirraaj** [comment]
@zoq Any comments about https://github.com/mlpack/jenkins-conf/issues/13#issuecomment-470646067.

**Comment by mirraaj** [comment]
@zoq One thing we can do is to find the files wherever changes have taken place. This is very easy because we can get the name of such files from the `diff` command. However, I am facing a huge issue after. Suppose we change codebase of some method, how to find the related test file? I am unable to think of any way of building a dependency graph that could be helpful here. If we are able to connect the codebase with respective test files, producing a script to tackle issue mlpack/mlpack#1741 will become handy. Please let me know how to tackle this.

@rcurtin @ShikharJ Your inputs are appreciated. Thanks

**Comment by zoq** [comment]
Agreed, I'm not sure if the output ``compile_commands.json``  would be helpful here, I guess you could just build with ``-DCMAKE_EXPORT_COMPILE_COMMANDS=ON`` and take a look at the output; by looking at: http://ci.mlpack.org/view/pull%20requests/job/pull-requests-mlpack-static-code-analysis/ws/build/compile_commands.json/*view*/ we might have to disable cotire to get something useful.

**Comment by zoq** [comment]
If we can't find something, we could also build the dependency graph just by looking at the includes.

**Comment by zoq** [comment]
One more idea would be to just tell jenkins to run a specific test multiple times.

**Comment by mirraaj** [comment]
@zoq I think its better to use `namespace` than `include` to check for the test cases. Not all test files, includes all the file name. For example, https://github.com/mlpack/mlpack/blob/master/src/mlpack/tests/distribution_test.cpp doesn't include all the distribution files. Instead, it just includes the namespace `distribution`. To deal with such situation, I grabbed all the namespace for files where changes took place (excluding files in the `tests` directory).

After grabbing all such namespace, I went ahead and added test present in all such tests, where the specific namespaces contribute. After looking for such files, I add all the tests in the file to a python dictionary. 

This method is lengthy because we also add a good number of test cases. However, using this method, it becomes easy to neglect a lot many test cases.  I hope I am able to explain my implementation. Please have a look at https://drive.google.com/open?id=1hoTbuohlHhUA2i7eRSP0r85lPsjrOPdq.

The code snippet is
```
#!/usr/bin/env python

#### Step 1 : Include Library and define repository paths. #####

# Import GitPython to compare results
import git

import os, time

# Extract all test files
import glob
# Link to GitHub Repo
# Use os.join_dir to make it universal
repo_dir = "/home/zoro/gsoc/mlpack"

repo = git.Repo(repo_dir)

# Check that the repository is not bare
assert not repo.bare

#### Step 2 : Define Branch latest commit and compare it to head. ####

#Assume that master branch is passing all the test
examine_branch_commit = repo.head.commit

commits = list(repo.iter_commits(examine_branch_commit, max_count=100))

author = commits[0].author.name

for commit in commits:
    if commit.author.name!=author:
        parent_branch_commit = commit
        break

diff_results = repo.git.diff(parent_branch_commit,\
    examine_branch_commit)

diff_results = diff_results.split('\n')

#### Step 3 : Define variable for storing different values. ####
newtests = [] # Stores new tests added in the tests directory.
filenames = [] # All file names where changes took place
namespace = [] # All namespace, where changes took place. This will
               # only include changes made outside tests directory.
testfilenames = [] # To store all test files to run simultaneously.

# Each added line has '+' in the beginning of the line
# Each deleted line has '-' in the beginning of the line
# Check if "BOOST_AUTO_TEST_CASE" is there in line added.
# If new test added, save the name of the test file

#### Step 4 : Grab new tests and file names where changes took place. ####

for line in diff_results:
    if line[0] == "+":
        if 'BOOST_AUTO_TEST_CASE' in line:
            newtests.append(line[22:-1])
    # Save filenames altered in the diff.
    if line[0:3] == "+++" or line[0:3] == "---":
        if line[6:] not in filenames:
            filenames.append(line[6:])


#### Step 5 : Define different functions required. ####

# This function checks if line contains a namespace or not.
def returnNamespace(line):
    nspace = ''
    check = False
    if 'namespace' in line:
        # Remove newline tab
        line = line[:-1]
        # Split line to get words
        line = line.split(' ')
        for i in range(len(line)):
            if line[i] == 'namespace' and i<len(line) - 1:
                nspace = line[i+1]
                # Remove similar namespace with form,
                # mlpack::namespace or namspace;
                # Since we are interating lines, we need to
                # take care of these
                if "mlpack::" in nspace:
                    nspace = nspace[8:]
                if nspace[-1] == ';':
                    nspace = nspace[:-1]
                if nspace!='mlpack':
                   check = True
    return check, nspace

# Grab boost auto test case from any '*_test.cpp' file.
def getBoostTestCase(fileline):
    testname = []
    for line in fileline:
        if 'BOOST_AUTO_TEST_CASE' in line:
            testname.append(line[22:-1])
    return testname


#### Step 6 : Grab changes in namespace taking place outside tests dir. ####
for fname in filenames:
    # If filenames contain a test file, add it to test file
    # name.
    if '_test.cpp' in fname:
        testfilenames.append(fname)
        continue
    file = open(fname, 'r')
    fileline = file.readlines()
    for line in fileline:
        check, nspace = returnNamespace(line)
        if check and nspace not in namespace:
            namespace.append(nspace)
    file.close()
# print namespace
# print include

# Now we have names of namespace and include from the script
# above. Next step is to add all the test cases related to
# such namespace and includes.

#### Step 7 : Look for changes test files which are relevant for the PR. ####
test_dir_files = 'src/mlpack/tests/*_test.cpp'

all_testfilenames = glob.glob(test_dir_files)

# If a test file has a namespace add it to the list of testfiles
# to be run 1000 times.

for fname in all_testfilenames:
    # Do not add twice if a test file is already changed in a PR.
    if fname in testfilenames:
        continue
    file = open(fname, 'r')
    fileline = file.readlines()
    for line in fileline:
        check, nspace = returnNamespace(line)
        # If there exists a namespace in the line, check the further condition.
        if check and nspace in namespace:
            testfilenames.append(fname)

# Store all the test name as a dictionary 
boostTestCaseDict = {}

# Add new tests to boost dictionary.
for n in newtests:
    if n not in boostTestCaseDict.keys():
        boostTestCaseDict[n] = 1

# Add tests of important files in the dictionary.
for fname in testfilenames:
    file = open(fname, 'r')
    fileline = file.readlines()
    testname = getBoostTestCase(fileline)
    for n in testname:
        if n not in boostTestCaseDict.keys():
            boostTestCaseDict[n] = 1        

print len(boostTestCaseDict.keys())

# Step 8 : Run 100 times all the important testcases.
```

**Comment by mirraaj** [comment]
The file clearly justifies all the steps in the python file. Naturally, this file has paths and targets set to my local machine. Since I haven't worked on Jenkins before, I think it will be better if you could add the paths to the script before merging this to the repository. Thanks

Also let me know if anyone knows a easier solution for this issue.

**Comment by mirraaj** [comment]
Also, I personally think it's better to use `classname` than `namespace`. Using `classname`, will definitely help us get rid of a lot of redundant test cases. But I am not sure if we will miss any important `testcase` using this approach. @zoq @ShikharJ @rcurtin Do you have any say over this idea?

**Comment by zoq** [comment]
The namespace approach probably includes a bunch of unnecessary tests, a change in the ``ann`` namespace will trigger all ann tests, which might take some time if we run each like 1000 times. Using the ``classname`` might be useful, have to think about a better strategy. Besides I don't think we will find a solution that will catch everything, on the one side it would be great if the necessary tests get selected automatically on the other side we should aim for a reasonable test time.

**Comment by mirraaj** [comment]
I believe that we might miss a few test cases using such an approach. The current implementation is definitely time taking but it considers all important test cases. To be frank, there are certain files which depend on other files for its definition. We may miss tests involving these files using `classname` approach. However, I do not have any example to prove my case as of now. 

@rcurtin @ShikharJ Please let me know your views. I will go ahead and make the necessary changes if this idea suits the purpose.
