### ISSUE TITLE
build directories are 3GB!

### ISSUE THREAD

**Issue by rcurtin** [mlpack/jenkins-conf#6]
```
{ ryan@masterblaster }{ /home/jenkins/jobs/mlpack - git commit test/workspace } $ du -h --max-depth=1
964K    ./reports
2.3M    ./test-support
2.6G    ./build
255M    ./repo
2.9G    .
```

We (or I) should investigate why it takes up so much space.  A clue:

```
{ ryan@masterblaster }{ /home/jenkins/jobs/mlpack - git commit test/workspace/build/bin } $ ls -lh mlpack_knn
-rwxr-xr-x 1 jenkins jenkins 79M Aug 25 16:08 mlpack_knn
```

79MB!  Clearly this is way larger than it should be.

**Comment by reallysaurabh** [comment]
I think we can close this issue now!

**Comment by zoq** [comment]
Oh, do we have a solution for the issue?

**Comment by reallysaurabh** [comment]
@zoq No, sorry I thought this was opened at some point earlier, where we have a huge workspace in Jenkins job. But, this is something else. Sorry, my bad!

**Comment by rcurtin** [comment]
Apparently this has gotten better over the years---I am now seeing build directories of less than 1GB.  So I think we can close this.
